import type { Metadata } from "next";
import { Geist, Geist_Mono, Sniglet } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { UserProvider } from "@/context/userContext";
import LogInWrapper from "@/components/LogIn/wrapper";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sniglet = Sniglet({
  subsets: ["latin"],
  weight: ["400", "800"],
  variable: "--font-sniglet",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${sniglet.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#FFF0D6]">
        <UserProvider>
          <Header />
          <LogInWrapper children={children} />
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
